CREATE TABLE IF NOT EXISTS ip_hash (
    ip_address VARCHAR(45) NOT NULL PRIMARY KEY,
    hashcode VARCHAR(64) NOT NULL UNIQUE,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);